name = "StableArrays"
uuid = "410f75ac-1911-4c82-9455-fb83a56c6096"
authors = ["St Z <abczst@outlook.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.4"
